CREATE TABLE IF NOT EXISTS CATEGORY_QUESTION_JT (
    FK_CATEGORY INT NOT NULL,
    FK_QUESTION INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(FK_CATEGORY) REFERENCES CATEGORY(ID),
    FOREIGN KEY(FK_QUESTION) REFERENCES QUESTION(ID),
    PRIMARY KEY(FK_CATEGORY, FK_QUESTION)
)