CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)