SELECT 
    A.ID, A.BODY, Q.FK_ANSWER
FROM        
    QUESTION_ANSWER_JT QAJ
INNER JOIN  
    QUESTION Q
ON
    Q.ID = QAJ.FK_QUESTION
INNER JOIN
    ANSWER A
ON
    A.ID = QAJ.FK_ANSWER
WHERE
    QAJ.FK_QUESTION = 1
