-- SQLite
CREATE TABLE IF NOT EXISTS QUESTION (
    ID INTEGER PRIMARY KEY,
    HASH_ID CHAR(32) NOT NULL UNIQUE,
    BODY TEXT NOT NULL,
    FK_ANSWER INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(FK_ANSWER) REFERENCES ANSWER(ID)
)